# Generated by Django 5.1.2 on 2025-01-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0002_party_guest_gift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="party_time",
            field=models.TimeField(),
        ),
    ]
